### PR TITLE
Indicated defunct links amongst online analyzers

### PR DESCRIPTION
**Pull request by SITZ**
Many links seem to be broken. Marked items from first section, which don't work.

### CODE REVIEW

**Comment by ashishb** [comment]
Thanks for the contribution. Can you please move the defunct links to the bottom of the list (in the same section)?

**Comment by SITZ** [comment]
@ashishb I didn't remove the links wondering what is the correct way to handle this. Do you want to keep the dead links or remove them altogether?

**Comment by ashishb** [comment]
I keep them around but move them towards the bottom of the list.

Ashish


On Fri, Apr 1, 2016 12:24 AM, Sitesh Shrivastava notifications@github.com wrote:
@ashishb I didn't remove the links wondering what is the correct way to handle this. Do
you want to keep the dead links or remove them altogether?

**Comment by SITZ** [comment]
Alright. Let me update the PR.

**Pull request merged**
