### PR TITLE
Added 'Inspeckage'

### PR DESCRIPTION
**Pull request by osospeed**

### CODE REVIEW

**Comment by ashishb** [comment]
Thanks for the contribution. Since it relies on Xposed, how about adding it immediately after Entry #12 (Xposed)?

**Comment by osospeed** [comment]
yes, or make a subcategory for Xposed based tools.

**Comment by ashishb** [comment]
Yeah, I will make one, once there are enough Xposed modules. For now, please add it immediately after Xposed.

**Comment by osospeed** [comment]
Done in #57.
Please close this PR.

**Pull request closed without merging**
