### PR TITLE
Added 'DECAF', Updated 'Droidscope'

### PR DESCRIPTION
**Pull request by osospeed**

### CODE REVIEW

**Comment by ashishb** [comment]
Thanks for the contribution @osospeed , I wonder if we should combine DECAF and Droidscope into a single entry.

**Comment by osospeed** [comment]
Yes. Feel free to modify it.

**Comment by ashishb** [comment]
Can you please modify the diff, so that, I can merge it as-is?

Ashish






On Sat, Aug 27, 2016 4:40 PM, O . S . O notifications@github.com wrote:
Yes. Feel free to modify it.

**Comment by osospeed** [comment]
I created a new PR [https://github.com/ashishb/android-security-awesome/pull/50]. Since I deleted the old fork.
Please close his PR.

**Comment by ashishb** [comment]
This has been merged via a different commit.

**Pull request closed without merging**
