### PR TITLE
add new sample source,MalGenome-a free malware datasets and  VirusTotal Malware Intelligence Service

### PR DESCRIPTION
**Pull request by tuomao**

### CODE REVIEW

**Comment by ashishb** [comment]
Can you please change number 5 to?

5. [MalGenome](http://www.malgenomeproject.org/policy.html) - contains 1260 malware samples categorized into 49 different malware families, free for research purpose.

Is there any easy way for a security person to apply for VirusTotal
+6. [VirusTotal Malware Intelligence Service](https://www.virustotal.com/en/about/terms-of-service/) - powered by ViusTotal,not free

**Comment by tuomao** [comment]
Yes,for number 5,I can changed it as your describe.
for number 6,actually ,you can apply for the service by email to them. https://www.virustotal.com/en/about/contact/ .

**Comment by ashishb** [comment]
@tuomao Did you push the commit?

**Comment by tuomao** [comment]
yes

**Comment by ashishb** [comment]
Merged, thanks.

**Pull request merged**
