### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sergey-wowwow**

### CODE REVIEW

**Comment by ashishb** [comment]
@sergey-wowwow Thanks for the contribution but there are 1000+ such vulnerabilities, I am not sure we should list all of them here.

**Comment by ashishb** [comment]
@sergey-wowwow Thanks for the contribution but there are 1000+ such vulnerabilities, I am not sure we should list all of them here.

**Comment by sergey-wowwow** [comment]
@ashishb 
That's impossible! I did a big research and found about a hundred. But the most of them reported years ago

**Comment by ashishb** [comment]
@sergey-wowwow Please create a new repo with at least 10+ vulnerability. I would be happy to link back to it.

**Pull request closed without merging**
