### PR TITLE
Added Appknox and Devknox

### PR DESCRIPTION
**Pull request by subho007**
Let me know if you need any changes 👍

### CODE REVIEW

**Comment by ashishb** [comment]
Thanks for the contribution. I left a comment, please address that and then I will merge.

**Comment by subho007** [comment]
Hi @ashishb I couldn't find your comment in this PR. Can you point out what needs to be fixed :)

**Comment by ashishb** [comment]
It was in pending state :|
Just submitted.


Ashish

**Comment by subho007** [comment]
@ashishb no issues 😄 

I have moved it to number four according to your suggestions 👍

**Pull request merged**
